services:
  - type: web
    name: youraya_telebot
    env: python
    plan: free
    runtime: python3
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python BotFactAio.py"
    envVars:
      - key: TOKEN
        value: ${TOKEN}