services:
  - type: worker
    name: botfactaio
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    envVars:
      - key: BOT_TOKEN
        fromDatabase: true