services:
  - type: web
    name: youraya_telebot
    env: python
    plan: free
    runtime: python3
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python BotFactAio.py"
    envVars:
      - key: BOT_TOKEN
        value: ${BOT_TOKEN}
      - key: PORT
        value: 10000  # Установите значение порта по умолчанию